// <auto-generated />
using GymMs.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymMs.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240215060729_SubscriptionStatusUserTb")]
    partial class SubscriptionStatusUserTb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymMs.Models.EmployeesM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gander")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TbEmployees");

                    b.HasData(
                        new
                        {
                            ID = 111,
                            Age = 26,
                            Email = "momen@gmail.com",
                            Gander = "Male",
                            Job = "Trainer",
                            Name = "Momen Maher",
                            Password = "Mo1234",
                            Phone = "0100123776"
                        },
                        new
                        {
                            ID = 1112,
                            Age = 24,
                            Email = "ainforma@gmail.com",
                            Gander = "Male",
                            Job = "Trainer",
                            Name = "Ahmed Ali",
                            Password = "aan1234",
                            Phone = "0100124476"
                        },
                        new
                        {
                            ID = 113,
                            Age = 25,
                            Email = "kkkn@gmail.com",
                            Gander = "Female",
                            Job = "Trainer",
                            Name = "Kamilya Nader",
                            Password = "k1234",
                            Phone = "0100333776"
                        });
                });

            modelBuilder.Entity("GymMs.Models.UserM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gander")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TbUsers");

                    b.HasData(
                        new
                        {
                            ID = 124,
                            Age = 22,
                            Email = "yousefmo@gmail.com",
                            Gander = "Male",
                            Name = "Yousef Mohamed",
                            Password = "Yo1234",
                            Phone = "0100123456",
                            SubscriptionPlan = "Platinum",
                            SubscriptionStatus = "Active"
                        },
                        new
                        {
                            ID = 224,
                            Age = 27,
                            Email = "alimomo@gmail.com",
                            Gander = "Male",
                            Name = "Ali Mohamed",
                            Password = "ali1234",
                            Phone = "0100169456",
                            SubscriptionPlan = "Platinum",
                            SubscriptionStatus = "Active"
                        },
                        new
                        {
                            ID = 324,
                            Age = 23,
                            Email = "laylaqn@gmail.com",
                            Gander = "Female",
                            Name = "Layla Ahmed",
                            Password = "lili1234",
                            Phone = "0100128756",
                            SubscriptionPlan = "Gold",
                            SubscriptionStatus = "Active"
                        },
                        new
                        {
                            ID = 424,
                            Age = 25,
                            Email = "nadaazein@gmail.com",
                            Gander = "Female",
                            Name = "Nada Zein  ",
                            Password = "Na1234",
                            Phone = "0100119456",
                            SubscriptionPlan = "VIP",
                            SubscriptionStatus = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
